In [2]:
from google.colab import files 
uploaded=files.upload()

Saving Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2021.csv to Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2021.csv

In [8]:
"""
import pandas as pd
df_Comorbidity=pd.read_csv('Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2021.csv')
df_Comorbidity
"""
import io
import pandas as pd
import numpy as np
df_comorbidity=pd.read_csv(io.BytesIO(uploaded['Conditions_Contributing_to_COVID-19_Deaths__by_State_and_Age__Provisional_2020-2021.csv']))
df_comorbidity

        Data As Of  Start Date  ... Number of Mentions Flag
0       08/29/2021  01/01/2020  ...              540.0  NaN
1       08/29/2021  01/01/2020  ...             2405.0  NaN
2       08/29/2021  01/01/2020  ...             6367.0  NaN
3       08/29/2021  01/01/2020  ...            18048.0  NaN
4       08/29/2021  01/01/2020  ...            43677.0  NaN
...            ...         ...  ...                ...  ...
285655  08/29/2021  04/01/2021  ...              197.0  NaN
285656  08/29/2021  05/01/2021  ...              184.0  NaN
285657  08/29/2021  06/01/2021  ...               35.0  NaN
285658  08/29/2021  07/01/2021  ...               29.0  NaN
285659  08/29/2021  08/01/2021  ...              190.0  NaN

[285660 rows x 14 columns]

In [9]:

df_ComorbidityClass=df_comorbidity[['Group','Year','Month','Condition Group','Condition','ICD10_codes','Age Group','COVID-19 Deaths','Number of Mentions']].dropna()
df_ComorbidityClass=df_ComorbidityClass.rename(columns={'Condition Group':'ConditionGroup','Age Group':'AgeGroup','COVID-19 Deaths':'COVID-19Deaths','Number of Mentions':'NumberOfMentions'})
df_ComorbidityClass

           Group    Year  Month  ...  AgeGroup COVID-19Deaths NumberOfMentions
37260   By Month  2020.0    1.0  ...      0-24            0.0              0.0
37261   By Month  2020.0    2.0  ...      0-24            0.0              0.0
37262   By Month  2020.0    3.0  ...      0-24            9.0              9.0
37263   By Month  2020.0    4.0  ...      0-24           27.0             30.0
37264   By Month  2020.0    5.0  ...      0-24           19.0             19.0
...          ...     ...    ...  ...       ...            ...              ...
285655  By Month  2021.0    4.0  ...  All Ages          197.0            197.0
285656  By Month  2021.0    5.0  ...  All Ages          184.0            184.0
285657  By Month  2021.0    6.0  ...  All Ages           35.0             35.0
285658  By Month  2021.0    7.0  ...  All Ages           29.0             29.0
285659  By Month  2021.0    8.0  ...  All Ages          190.0            190.0

[177842 rows x 9 columns]

In [10]:
predict_Dictionry=dict(zip(df_ComorbidityClass.Condition.unique(),df_ComorbidityClass.ICD10_codes.unique()))
print(predict_Dictionry)

{'Influenza and pneumonia': 'J09-J18', 'Chronic lower respiratory diseases': 'J40-J47', 'Adult respiratory distress syndrome': 'J80', 'Respiratory failure': 'J96', 'Respiratory arrest': 'R09.2', 'Other diseases of the respiratory system': 'J00-J06, J20-J39, J60-J70, J81-J86, J90-J95, J97-J99, U04', 'Hypertensive diseases': 'I10-I15', 'Ischemic heart disease': 'I20-I25', 'Cardiac arrest': 'I46', 'Cardiac arrhythmia': 'I44, I45, I47-I49', 'Heart failure': 'I50', 'Cerebrovascular diseases': 'I60-I69', 'Other diseases of the circulatory system': 'I00-I09, I26-I43, I51, I52, I70-I99', 'Sepsis': 'A40-A41', 'Malignant neoplasms': 'C00-C97', 'Diabetes': 'E10-E14', 'Obesity': 'E65-E68', 'Alzheimer disease': 'G30', 'Vascular and unspecified dementia': 'F01, F03', 'Renal failure': 'N17-N19', 'Intentional and unintentional injury, poisoning, and other adverse events': 'S00-T98, V01-X59, X60-X84, X85-Y09, Y10-Y36, Y40-Y89, U01-U03', 'All other conditions and causes (residual)': 'A00-A39, A42-B99, D00-E07, E15-E64, E70-E90, F00, F02, F04-G26, G31-H95, K00-K93, L00-M99, N00-N16, N20-N98, O00-O99, P00-P96, Q00-Q99, R00-R08, R09.0, R09.1, R09.3, R09.8, R10-R99', 'COVID-19': 'U071'}

In [11]:
def enumera_condition(fila):
    cond=fila['Condition']
    if cond =='Influenza and pneumonia':
        r=1
        return r 
    else:
        if cond =='Chronic lower respiratory diseases':
            r=2
            return r 
        else:
            if cond =='Adult respiratory distress syndrome':
                r=3
                return r 
            else:
                if cond == 'Respiratory failure':
                    r=4
                    return r 
                else:
                    if cond == 'Respiratory arrest':
                        r=5
                        return r 
                    else:
                        if cond == 'Other diseases of the respiratory system':
                            r=6
                            return r 
                        else:
                            if cond == 'Hypertensive diseases':
                                r=7
                                return r 
                            else:
                                if cond == 'Ischemic heart disease':
                                    r=8
                                    return r 
                                else:
                                    if cond == 'Cardiac arrest':
                                        r=9
                                        return r 
                                    else:
                                        if cond == 'Cardiac arrhythmia':
                                            r=10
                                            return r 
                                        else:
                                            if cond == 'Heart failure':
                                                r=11
                                                return r 
                                            else:
                                                if cond == 'Cerebrovascular diseases':
                                                    r=12
                                                    return r 
                                                else:
                                                    if cond == 'Other diseases of the circulatory system':
                                                        r=13
                                                        return r 
                                                    else:
                                                        if cond == 'Sepsis':
                                                            r=14
                                                            return r 
                                                        else:
                                                            if cond == 'Malignant neoplasms':
                                                                r=15 
                                                                return r 
                                                            else:
                                                                if cond == 'Diabetes':
                                                                    r=16
                                                                    return r 
                                                                else:
                                                                    if cond == 'Obesity':
                                                                        r=17
                                                                        return r 
                                                                    else:
                                                                        if cond == 'Alzheimer disease':
                                                                            r=18
                                                                            return r 
                                                                        else:
                                                                            if cond == 'Vascular and unspecified dementia':
                                                                                r=19
                                                                                return r 
                                                                            else:
                                                                                if  cond == 'Renal failure':
                                                                                    r=20
                                                                                    return r 
                                                                                else:
                                                                                    if cond == 'Intentional and unintentional injury, poisoning, and other adverse events':
                                                                                        r=21
                                                                                        return r 
                                                                                    else:
                                                                                        if cond == 'All other conditions and causes (residual)':
                                                                                            r=22
                                                                                            return r 
                                                                                        else:
                                                                                            if cond == 'COVID-19':
                                                                                                r=23
                                                                                                return r 

df_ComorbidityClass['NumCond']=df_ComorbidityClass.apply(enumera_condition,axis=1)
df_ComorbidityClass

           Group    Year  Month  ... COVID-19Deaths NumberOfMentions NumCond
37260   By Month  2020.0    1.0  ...            0.0              0.0       1
37261   By Month  2020.0    2.0  ...            0.0              0.0       1
37262   By Month  2020.0    3.0  ...            9.0              9.0       1
37263   By Month  2020.0    4.0  ...           27.0             30.0       1
37264   By Month  2020.0    5.0  ...           19.0             19.0       1
...          ...     ...    ...  ...            ...              ...     ...
285655  By Month  2021.0    4.0  ...          197.0            197.0      23
285656  By Month  2021.0    5.0  ...          184.0            184.0      23
285657  By Month  2021.0    6.0  ...           35.0             35.0      23
285658  By Month  2021.0    7.0  ...           29.0             29.0      23
285659  By Month  2021.0    8.0  ...          190.0            190.0      23

[177842 rows x 10 columns]

In [12]:
df_ComorbidityClass['AgeGroup'].drop_duplicates()

37260          0-24
37280         25-34
37300         35-44
37320         45-54
37340         55-64
37360         65-74
37380         75-84
37400           85+
37420    Not stated
37440      All Ages
Name: AgeGroup, dtype: object

In [13]:
def enumera_codigo(fila):
    ic=fila['ICD10_codes']
    if ic=='J09-J18':
        r=1
        return r
    else:
        if ic=='J40-J47':
            r=2
            return r
        else:
            if ic=='J80':
                r=3
                return r 
            else:
                if ic=='J96':
                    r=4
                    return r
                else:
                    if ic=='R09.2':
                        r=5
                        return r 
                    else:
                        if ic=='J00-J06' or 'J20-J39' or 'J60-J70' or 'J81-J86' or 'J90-J95' or 'J97-J99' or 'U04':
                            r=6
                            return r 
                        else: 
                            if ic=='I10-I15' or 'I20-I25' or'I46' or 'I44' or 'I45' or 'I47-I49' or 'I50' or 'I60-I69':
                                r=7
                                return r 
                            else:
                                if ic=='I00-I09' or 'I26-I43' or 'I51' or 'I52' or 'I70-I99' or 'A40-A41' or 'C00-C97':
                                    r=8
                                    return r
                                else:
                                    if ic=='E10-E14' or 'E65-E68' or 'G30' or 'F01' or 'F03' or 'N17-N19':
                                        r=9
                                        return r 
                                    else:
                                        if ic=='S00-T98, V01-X59, X60-X84, X85-Y09, Y10-Y36, Y40-Y89, U01-U03':
                                            r=10
                                            return r 
                                        else:
                                            if ic=='A00-A39' or 'A42-B99' or 'D00-E07' or 'E15-E64' or 'E70-E90' or 'F00' or 'F02' or 'F04-G26' or 'G31-H95' or 'K00-K93' or 'L00-M99' or 'N00-N16' or 'N20-N98' or 'O00-O99' or 'P00-P96' or 'Q00-Q99' or 'R00-R08' or 'R09.0' or 'R09.1' or 'R09.3' or 'R09.8' or 'R10-R99':
                                                r=11
                                                return r
                                            else:
                                                if ic=='U071':
                                                    r=12
                                                    return r 
df_ComorbidityClass['NumCod']=df_ComorbidityClass.apply(enumera_codigo,axis=1)
df_ComorbidityClass

           Group    Year  Month  ... NumberOfMentions NumCond NumCod
37260   By Month  2020.0    1.0  ...              0.0       1      1
37261   By Month  2020.0    2.0  ...              0.0       1      1
37262   By Month  2020.0    3.0  ...              9.0       1      1
37263   By Month  2020.0    4.0  ...             30.0       1      1
37264   By Month  2020.0    5.0  ...             19.0       1      1
...          ...     ...    ...  ...              ...     ...    ...
285655  By Month  2021.0    4.0  ...            197.0      23      6
285656  By Month  2021.0    5.0  ...            184.0      23      6
285657  By Month  2021.0    6.0  ...             35.0      23      6
285658  By Month  2021.0    7.0  ...             29.0      23      6
285659  By Month  2021.0    8.0  ...            190.0      23      6

[177842 rows x 11 columns]

In [14]:
def enumeraedad(fila):
    ed=fila['AgeGroup']
    if ed=='0-24':
        r=1
        return r 
    else:
        if ed=='25-34':
            r=2
            return r
        else:
            if ed=='35-44':
                r=3
                return r 
            else:
                if ed=='45-54':
                    r=4 
                    return r 
                else:
                    if ed=='55-64':
                        r=5
                        return r 
                    else:
                        if ed=='65-74':
                            r=6
                            return r
                        else:
                            if ed=='75-84':
                                r=7
                                return r 
                            else:
                                if ed=='85+':
                                    r=8
                                    return r
                                else:
                                    if ed=='All Ages':
                                        r=9
                                        return r  
df_ComorbidityClass['RangoEdad']=df_ComorbidityClass.apply(enumeraedad,axis=1)
df_ComorbidityClass

           Group    Year  Month  ... NumCond NumCod RangoEdad
37260   By Month  2020.0    1.0  ...       1      1       1.0
37261   By Month  2020.0    2.0  ...       1      1       1.0
37262   By Month  2020.0    3.0  ...       1      1       1.0
37263   By Month  2020.0    4.0  ...       1      1       1.0
37264   By Month  2020.0    5.0  ...       1      1       1.0
...          ...     ...    ...  ...     ...    ...       ...
285655  By Month  2021.0    4.0  ...      23      6       9.0
285656  By Month  2021.0    5.0  ...      23      6       9.0
285657  By Month  2021.0    6.0  ...      23      6       9.0
285658  By Month  2021.0    7.0  ...      23      6       9.0
285659  By Month  2021.0    8.0  ...      23      6       9.0

[177842 rows x 12 columns]

In [15]:
df_ComorbidityClass.select_dtypes(include=['float64', 'int']).describe() #['NumCod'].max()

                Year          Month  ...         NumCod      RangoEdad
count  177842.000000  177842.000000  ...  177842.000000  153052.000000
mean     2020.370728       5.516863  ...       5.345858       4.800859
std         0.483001       3.284019  ...       1.405269       2.712043
min      2020.000000       1.000000  ...       1.000000       1.000000
25%      2020.000000       3.000000  ...       6.000000       2.000000
50%      2020.000000       5.000000  ...       6.000000       5.000000
75%      2021.000000       8.000000  ...       6.000000       7.000000
max      2021.000000      12.000000  ...       6.000000       9.000000

[8 rows x 7 columns]

In [16]:
df_ComorbidityClass=df_ComorbidityClass.dropna()
df_ComorbidityClass

           Group    Year  Month  ... NumCond NumCod RangoEdad
37260   By Month  2020.0    1.0  ...       1      1       1.0
37261   By Month  2020.0    2.0  ...       1      1       1.0
37262   By Month  2020.0    3.0  ...       1      1       1.0
37263   By Month  2020.0    4.0  ...       1      1       1.0
37264   By Month  2020.0    5.0  ...       1      1       1.0
...          ...     ...    ...  ...     ...    ...       ...
285655  By Month  2021.0    4.0  ...      23      6       9.0
285656  By Month  2021.0    5.0  ...      23      6       9.0
285657  By Month  2021.0    6.0  ...      23      6       9.0
285658  By Month  2021.0    7.0  ...      23      6       9.0
285659  By Month  2021.0    8.0  ...      23      6       9.0

[153052 rows x 12 columns]

In [20]:
# Tratamiento de datos
# ==============================================================================
import numpy as np
import pandas as pd
from tabulate import tabulate

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns

# Preprocesado y modelado
# ==============================================================================
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_blobs
from sklearn.metrics import euclidean_distances
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Ridge

#from skopt.space import Real, Integer
#from skopt.utils import use_named_args
#from skopt import gp_minimize
#from skopt.plots import plot_convergence

# Varios
# ==============================================================================
import multiprocessing
import random
from itertools import product
#from fitter import Fitter, get_common_distributions

In [21]:
from sklearn.model_selection import train_test_split
#X=df_ComorbidityClass['']
#y=df_ComorbidityClass[''] 
X_train, X_test, y_train, y_test = train_test_split(
                                        df_ComorbidityClass.drop('NumCond', axis = 'columns'),
                                        df_ComorbidityClass['NumCond'],
                                        train_size   = 0.8,
                                        random_state = 1234,
                                        shuffle      = True
                                    )

In [24]:
# Selección de las variables por típo
# ==============================================================================
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector

# Se estandarizan las columnas numéricas y se hace one-hot-encoding de las 
# columnas cualitativas. Para mantener las columnas a las que no se les aplica 
# ninguna transformación se tiene que indicar remainder='passthrough'.
numeric_cols = X_train.select_dtypes(include=['float64', 'int']).columns.to_list()
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.to_list()

preprocessor = ColumnTransformer(
                   [('scale', StandardScaler(), numeric_cols),
                    ('onehot', OneHotEncoder(handle_unknown='ignore'), cat_cols)],
                remainder='passthrough')

In [25]:
X_train_prep = preprocessor.fit_transform(X_train)
X_test_prep  = preprocessor.transform(X_test)

In [28]:
# Convertir el output en dataframe y añadir el nombre de las columnas
# ==============================================================================
encoded_cat = preprocessor.named_transformers_['onehot'].get_feature_names(cat_cols)
labels = np.concatenate([numeric_cols, encoded_cat])
datos_train_prep = preprocessor.transform(X_train)
#datos_train_prep = pd.DataFrame(datos_train_prep, columns=labels)
#datos_train_prep.info()

In [29]:
# Selección de las variables por típo
# ==============================================================================
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_selector

numeric_cols = X_train.select_dtypes(include=['float64', 'int']).columns.to_list()
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.to_list()

# Transformaciones para las variables numéricas
numeric_transformer = Pipeline(
                        steps=[
                            ('imputer', SimpleImputer(strategy='median')),
                            ('scaler', StandardScaler())
                        ]
                      )


# Transformaciones para las variables categóricas
categorical_transformer = Pipeline(
                            steps=[
                                ('imputer', SimpleImputer(strategy='most_frequent')),
                                ('onehot', OneHotEncoder(handle_unknown='ignore'))
                            ]
                          )

preprocessor = ColumnTransformer(
                    transformers=[
                        ('numeric', numeric_transformer, numeric_cols),
                        ('cat', categorical_transformer, cat_cols)
                    ],
                    remainder='passthrough'
                )

In [30]:
X_train_prep = preprocessor.fit_transform(X_train)
X_test_prep  = preprocessor.transform(X_test)

In [33]:
from sklearn.linear_model import Ridge

# Preprocedado
# ==============================================================================

# Identificación de columnas numéricas y categóricas
numeric_cols = X_train.select_dtypes(include=['float64', 'int']).columns.to_list()
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.to_list()


# Transformaciones para las variables numéricas
numeric_transformer = Pipeline(
                        steps=[('scaler', StandardScaler())]
                      )

# Transformaciones para las variables categóricas
categorical_transformer = Pipeline(
                            steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))]
                          )

preprocessor = ColumnTransformer(
                    transformers=[
                        ('numeric', numeric_transformer, numeric_cols),
                        ('cat', categorical_transformer, cat_cols)
                    ],
                    remainder='passthrough'
                )

# Pipeline
# ==============================================================================

# Se combinan los pasos de preprocesado y el modelo en un mismo pipeline
pipe = Pipeline([('preprocessing', preprocessor),
                 ('modelo', Ridge())])

# Train
# ==============================================================================
# Se asigna el resultado a _ para que no se imprima por pantalla
_ = pipe.fit(X=X_train, y=y_train)

In [34]:
# Validación cruzada
# ==============================================================================
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
                estimator = pipe,
                X         = X_train,
                y         = y_train,
                scoring   = 'neg_root_mean_squared_error',
                cv        = 5
             )

print(f"Métricas validación cruzada: {cv_scores}")
print(f"Média métricas de validación cruzada: {cv_scores.mean()}")

Métricas validación cruzada: [-0.00965054 -0.00680739 -0.00818973 -0.00785258 -0.01523194]
Média métricas de validación cruzada: -0.009546435832609574

In [35]:
predicciones = pipe.predict(X_test)
predicciones

array([12.98848146,  6.99601184, 22.9941932 , ...,  6.00046681,
       17.00188231,  5.00036168])

In [36]:
# Se crea un dataframe con las predicciones y el valor real
df_predicciones = pd.DataFrame({'NumCond' : y_test, 'predicción' : predicciones})
df_predicciones

        NumCond  predicción
232863       13   12.988481
204092        7    6.996012
92326        23   22.994193
252856       20   20.003174
257283       20   20.000652
...         ...         ...
229093       17   16.999203
257376       20   19.996612
93480         6    6.000467
210857       17   17.001882
208283        5    5.000362

[30611 rows x 2 columns]

In [38]:
from sklearn.model_selection import RandomizedSearchCV, RepeatedKFold
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
import multiprocessing

# Pipeline: preprocesado + modelo
# ==============================================================================
# Identificación de columnas numéricas y catégoricas
numeric_cols = X_train.select_dtypes(include=['float64', 'int']).columns.to_list()
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.to_list()

In [39]:
# Transformaciones para las variables numéricas
numeric_transformer = Pipeline(
                        steps=[('scaler', StandardScaler())]
                      )

In [40]:
# Transformaciones para las variables categóricas
categorical_transformer = Pipeline(
                            steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))]
                          )

In [41]:
preprocessor = ColumnTransformer(
                    transformers=[
                        ('numeric', numeric_transformer, numeric_cols),
                        ('cat', categorical_transformer, cat_cols)
                    ],
                    remainder='passthrough'
                )

In [42]:
# Se combinan los pasos de preprocesado y el modelo en un mismo pipeline.
pipe = Pipeline([('preprocessing', preprocessor),
                 ('modelo', KNeighborsRegressor())])

In [43]:
# Optimización de hiperparámetros
# ==============================================================================
# Espacio de búsqueda de cada hiperparámetro
param_distributions = {'modelo__n_neighbors': np.linspace(1, 100, 500, dtype=int)}

# Búsqueda random grid
grid = RandomizedSearchCV(
        estimator  = pipe,
        param_distributions = param_distributions,
        n_iter     = 20,
        scoring    = 'neg_root_mean_squared_error',
        n_jobs     = multiprocessing.cpu_count() - 1,
        cv         = RepeatedKFold(n_splits = 5, n_repeats = 3), 
        refit      = True, 
        verbose    = 0,
        random_state = 123,
        return_train_score = True
       )

grid.fit(X = X_train, y = y_train)

# Resultados del grid
# ==============================================================================
resultados = pd.DataFrame(grid.cv_results_)
resultados.filter(regex = '(param.*|mean_t|std_t)')\
    .drop(columns = 'params')\
    .sort_values('mean_test_score', ascending = False)\
    .head(1)

# Gráfico resultados validación cruzada para cada hiperparámetro
# ------------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(6, 3.84))
hiperparametro = 'param_modelo__n_neighbors'
resultados = resultados.sort_values(hiperparametro, ascending = False)
metrica    = grid.scoring

resultados.plot(hiperparametro, 'mean_train_score', ax=ax)
resultados.plot(hiperparametro, 'mean_test_score', ax=ax)
ax.fill_between(resultados[hiperparametro].astype(np.int),
                resultados['mean_train_score'] + resultados['std_train_score'],
                resultados['mean_train_score'] - resultados['std_train_score'],
                alpha=0.2)
ax.fill_between(resultados[hiperparametro].astype(np.int),
                resultados['mean_test_score'] + resultados['std_test_score'],
                resultados['mean_test_score'] - resultados['std_test_score'],
                alpha=0.2)
ax.legend()
ax.set_title('Evolución del error CV')
ax.set_ylabel(metrica);

fig, ax = plt.subplots(figsize=(8, 5))

resultados = resultados.sort_values('mean_test_score', ascending = True)

ax.barh(
    [str(d) for d in resultados['params']],
    resultados['mean_test_score'],
    xerr=resultados['std_test_score'],
    align='center',
    alpha=0
)
ax.plot(
    resultados['mean_test_score'],
    [str(d) for d in resultados['params']],
    marker="D",
    linestyle="",
    alpha=0.8,
    color="r"
)
ax.set_title('Comparación de Hiperparámetros')
ax.set_ylabel(metrica);